version: '3.8'

services:
  app:
    image: updates:2
    container_name: timesheet
    ports:
      - "3000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/weeklyupdatesDB

  mongo:
    image: mongo:7.0.12
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
