version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always
    env_file:
      - .env
    networks:
      - updates-network

  mongo:
    image: mongo:7.0.12
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - updates-network


  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express-updates
    ports:
      - "3000:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false      
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      - mongo
    networks:
      - updates-network

volumes:
  mongo-data:

networks:
  updates-network:
